.PHONY : clean

all : Term.java True.java False.java Zero.java Succ.java Pred.java IsZero.java If.java Type.java TypeErrorException.java Tests.java
	javac Term.java True.java False.java Zero.java Succ.java Pred.java IsZero.java If.java Type.java TypeErrorException.java Tests.java

# to run tests, compile and run "java Tests"

clean :
	rm *.class